#+TITLE: i3 Window Manager Configuration
#+LANGUAGE: en
#+AUTHOR: David Álvarez Rosa
#+EMAIL: david@alvarezrosa.com
#+DESCRIPTION: My personal i3 Window Manager configuration file.
#+PROPERTY: header-args :tangle config


i3 is a tiling window manager, completely written from scratch. The target
platforms are GNU/Linux and BSD operating systems, the code is Free and Open
Source Software (FOSS) under the BSD license. i3 is primarily targeted at
advanced users and developers. This is my personal configuration, primarily
based on the principles of minimalism (simplicity is the key for success). All
key bindings are set following the holy Emacs philosophy.

* Theme
Set default font (for window title).
#+begin_src conf
  font pango:mono 11
#+end_src

Set initial inner and outer gaps.
#+begin_src conf
  gaps inner 6
  gaps outer 4
#+end_src

Set window border to 1 pixel.
#+begin_src conf
  new_window 1pixel
  default_border pixel 1
#+end_src

* Functionality
Set modifier key to Super (Windows key).
#+begin_src conf
  set $mod Mod4
#+end_src

Disable focus wrapping (I have always found this feature annoying).
#+begin_src conf
  focus_wrapping no
#+end_src

Set workspace names.
#+begin_src conf
  set $ws1 "1. Emacs"
  set $ws2 "2. Browser"
  set $ws3 "3. Terminal"
  set $ws4 "4. Ranger"
  set $ws5 "5. Communication"
  set $ws6 "6. Executing"
  set $ws7 "7. Media"
  set $ws8 "8. Firefox"
  set $ws9 "9. Auxiliar"
  set $ws10 "10. Workspace"
#+end_src

* Key bindings
** General
Key bindings related to i3wm, such as reloading the configuration, restarting,
or ending the X session.
#+begin_src conf
  bindsym $mod+Shift+c reload
  bindsym $mod+Shift+r restart
  bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"
#+end_src

Open a terminal.
#+begin_src conf
  bindsym $mod+Return exec i3-sensible-terminal
#+end_src

Toggle status bar.
#+begin_src conf
  bindsym $mod+m bar mode toggle
#+end_src

** Workspaces
Key bindings related to workspaces.

Switching to a workspace.
#+begin_src conf
  bindsym $mod+1 workspace $ws1
  bindsym $mod+2 workspace $ws2
  bindsym $mod+3 workspace $ws3
  bindsym $mod+4 workspace $ws4
  bindsym $mod+5 workspace $ws5
  bindsym $mod+6 workspace $ws6
  bindsym $mod+7 workspace $ws7
  bindsym $mod+8 workspace $ws8
  bindsym $mod+9 workspace $ws9
  bindsym $mod+0 workspace $ws10
#+end_src

Moving a container/window to a workspace.
#+begin_src conf
  bindsym $mod+Shift+1 move container to workspace $ws1
  bindsym $mod+Shift+2 move container to workspace $ws2
  bindsym $mod+Shift+3 move container to workspace $ws3
  bindsym $mod+Shift+4 move container to workspace $ws4
  bindsym $mod+Shift+5 move container to workspace $ws5
  bindsym $mod+Shift+6 move container to workspace $ws6
  bindsym $mod+Shift+7 move container to workspace $ws7
  bindsym $mod+Shift+8 move container to workspace $ws8
  bindsym $mod+Shift+9 move container to workspace $ws9
  bindsym $mod+Shift+0 move container to workspace $ws10
#+end_src

Switching between the last two used workspaces.
#+begin_src conf
  bindsym $mod+Tab workspace back_and_forth
#+end_src

*** Default Workspaces
Open =mpv= in a window video for multitasking.
#+begin_src conf
  for_window [class="mpv"]                 floating enable; exec --no-startup-id ~/.local/bin/bottomright
  for_window [class="mpv"]                 sticky enable
#+end_src

** Windows
Key bindings related to windows (inside a workspace).

Killing current window.
#+begin_src conf
  bindsym $mod+q kill
#+end_src

*** Window focus
Set key bindings for changing window focus (following the holy Emacs "bfnp"
moving set).
#+begin_src conf
  bindsym $mod+b focus left
  bindsym $mod+n focus down
  bindsym $mod+p focus up
  bindsym $mod+f focus right
#+end_src

Alternative with arrow keys.
#+begin_src conf
  bindsym $mod+Left focus left
  bindsym $mod+Down focus down
  bindsym $mod+Up focus up
  bindsym $mod+Right focus right
  #+end_src

Change focus between tiling/floating windows.
#+begin_src conf
  bindsym $mod+space focus mode_toggle
#+end_src

*** Window moving
Set key bindings for moving windows around with same commands as window focus,
but with =Shift= modifier.
#+begin_src conf
  bindsym $mod+Shift+b move left 20px
  bindsym $mod+Shift+n move down 20px
  bindsym $mod+Shift+p move up 20px
  bindsym $mod+Shift+f move right 20px
#+end_src

Alternative with arrow keys.
#+begin_src conf
  bindsym $mod+Shift+Left move left 20px
  bindsym $mod+Shift+Down move down 20px
  bindsym $mod+Shift+Up move up 20px
  bindsym $mod+Shift+Right move right 20px
#+end_src

Use $mod+Mouse for moving floating windows.
#+begin_src conf
  floating_modifier $mod
#+end_src

*** Window resize
Set key bindings for window resizing with same commands as window focus, but
with =Control= modifier.
  #+begin_src conf
  bindsym $mod+Control+f exec --no-startup-id "~/.local/bin/i3resize right"
  bindsym $mod+Control+p exec --no-startup-id "~/.local/bin/i3resize up"
  bindsym $mod+Control+n exec --no-startup-id "~/.local/bin/i3resize down"
  bindsym $mod+Control+b exec --no-startup-id "~/.local/bin/i3resize left"
  #+end_src

Alternative with arrow keys.
  #+begin_src conf
    bindsym $mod+Control+Right exec --no-startup-id "~/.local/bin/i3resize right"
    bindsym $mod+Control+Upc exec --no-startup-id "~/.local/bin/i3resize up"
    bindsym $mod+Control+Down exec --no-startup-id "~/.local/bin/i3resize down"
    bindsym $mod+Control+Left exec --no-startup-id "~/.local/bin/i3resize left"
  #+end_src

*** Window splitting
Customize splitting direction for windows.
#+begin_src conf
  bindsym $mod+v split vertical
  bindsym $mod+h split horizontal
#+end_src

*** Window floating
Set key for the toggle between tiling/floating.
#+begin_src conf
  bindsym $mod+Shift+space floating toggle
#+end_src

*** Window sticky
Binding for sticky window toggle.
#+begin_src conf
  bindsym $mod+Shift+w sticky toggle
#+end_src

*** Window fullscreen
Binding for toggling window fullscreen.
#+begin_src conf
  bindsym $mod+o fullscreen toggle
#+end_src

*** Window video multitasking
The following creates a small floating sticky window in the bottom right of the
screen. Very useful for multitasking while watching a video (not recommended
for productivity, though).
#+begin_src conf
  bindsym $mod+Shift+v floating toggle; exec --no-startup-id ~/.local/bin/bottomright; sticky enable
#+end_src

* Status bar
Status bar configuration.
#+begin_src conf
  bar {
      font pango:mono 9
      status_command i3blocks
      position top
      mode dock
  }
#+end_src
