#+TITLE: Bash Configuration
#+LANGUAGE: en
#+AUTHOR: David Álvarez Rosa
#+EMAIL: david@alvarezrosa.com
#+DESCRIPTION: My personal Bash configuration file.
#+PROPERTY: header-args :tangle ~/.bashrc


If not running interactively, don't do anything.
#+begin_src bash
  case $- in
      ,*i*) ;;
      ,*) return;;
  esac
#+end_src

Allow automatic =cd= (change directory), i.e., typing just the directory name
is enough.
#+begin_src bash
  shopt -s autocd
#+end_src

Check the window size after each command and, if necessary, update the values
of LINES and COLUMNS.
#+begin_src bash
  shopt -s checkwinsize
#+end_src

Globstar matching.
#+begin_src bash
  shopt -s globstar
#+end_src

Enable completion features for the following commands.
#+begin_src bash
  complete -c man which whereis
  complete -cf sudo
#+end_src

Update "PATH" variable so scripts inside =.local/bin/global= can be executed.
#+begin_src bash
  PATH="$PATH:$HOME/.local/bin/global"
#+end_src

Enable programmable completion features (you don't need to enable this, if it's
already enabled in /etc/bash.bashrc and /etc/profile sources /etc/bash.bashrc).
#+begin_src bash
  if ! shopt -oq posix; then
      if [ -f /usr/share/bash-completion/bash_completion ]; then
          . /usr/share/bash-completion/bash_completion
      elif [ -f /etc/bash_completion ]; then
          . /etc/bash_completion
      fi
  fi
#+end_src

Bash prompt configuration.
#+begin_src bash
  if [ "$EUID" -ne 0 ]
  then
      export PS1="\[$(tput bold)\]\[$(tput setaf 1)\][\[$(tput setaf 3)\]\u\[$(tput setaf 2)\]@\[$(tput setaf 4)\]\h\[$(tput setaf 7)\] Arch Linux  \[$(tput setaf 5)\]\w\[$(tput setaf 1)\]]\[$(tput setaf 7)\]\n  \\$ \[$(tput sgr0)\]"
  else
      export PS1="\[$(tput bold)\]\[$(tput setaf 1)\][\[$(tput setaf 3)\]ROOT\[$(tput setaf 2)\]@\[$(tput setaf 4)\]$(hostname | awk '{print toupper($0)}')\[$(tput setaf 7)\] Arch Linux  \[$(tput setaf 5)\]\w\[$(tput setaf 1)\]]\[$(tput setaf 7)\]\n  \\$ \[$(tput sgr0)\]"
  fi

#+end_src

Configure bash history.
#+begin_src bash
  export HISTCONTROL=ignoreboth
  shopt -s histappend
  export HISTSIZE=5000
  export HISTFILESIZE=5000
#+end_src

Enable colors for the following commands.
#+begin_src bash
  # Colores
  eval "$(dircolors)"
  alias ls="ls -hN --color=auto --group-directories-first -v --time-style='+%d %b %H:%M'"
  alias l="exa --icons --group-directories-first"
  alias ll="l -lag"
  alias grep="grep --color"
  alias diff="diff --color"

#+end_src

Set aliases for basic commands (among them, make =mv= and =cp= interactive).
#+begin_src bash
  alias sp-Syu="sp -Syu --noconfirm && pkill -RTMIN+1 i3blocks"
  alias ..='cd ..'
  alias ...='cd ../../'
  alias mv="mv -i"
  alias cp="cp -i"
#+end_src

More aliases.
#+begin_src bash
  alias cpc="xclip -selection clipboard"
  alias yt="youtube-dl --add-metadata -ic --output \"%(uploader)s%(title)s.%(ext)s\"" # Download video link
  alias yta="yt -x -f bestaudio/best" # Download only audio
#+end_src

Set up XDG Base Directory specification.
#+begin_src bash
  export XDG_CONFIG_HOME="$HOME/.config"
  export XDG_CACHE_HOME="$HOME/.cache"
  export XDG_DATA_HOME="$HOME/.local/share/"
#+end_src

Cleanup programs.
#+begin_src bash
  export LESSHISTFILE=-
  export HISTFILE="$XDG_DATA_HOME/history"
  export INPUTRC="$XDG_CONFIG_HOME/bash/inputrc"
  export UNISON="$XDG_CONFIG_HOME/unison"
#+end_src
