#+TITLE: Tridactyl Configuration (Mozilla Firefox Extension)
#+LANGUAGE: en
#+AUTHOR: David Álvarez Rosa
#+EMAIL: david@alvarezrosa.com
#+DESCRIPTION: My personal Tridactyl configuration file (is a Mozilla Firefox Extension).
#+PROPERTY: header-args :tangle ~/.config/tridactyl/tridactylrc


Tridacty replaces Firefox's default control mechanism with one modelled on the
one true editor, ~Vim~ Emacs. I have configured the extension to replicate all
the commands similarly to Emacs.

It is needed the change of default Firefox bindings like =<C-N>=. It is
impossible to change or disable that bindings, but it is possible to change the
modifier key used in that bindings instead. This can be done in about:config
page setting the variable ui.key.acceelKey to 91 (corresponds with the OS Left
key, also known as WinKey). Alternate keycodes can be found [[https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode][here]].

Of course, Firefox extension Tridactyl must be installed. In Arch Linux this
can be done with =pacman -S firefox-tridactyl=.

In Tridactyl enter to command mode with =:=, enter command “installnative” and
follow instructions.


* Bindings
Scroll.
#+begin_src fundamental
  bind n scrollline 5
  bind p scrollline -5
  bind <C-n> scrollline 5
  bind <C-p> scrollline -5
  bind <C-f> scrollpx 50
  bind <C-b> scrollpx -50
  bind <C-u><C-Space> jumpprev
  bind <C-v> scrollpage 1
  bind <A-v> scrollpage -1
  bind d scrollpage 1
  bind u scrollpage -1
  bind > scrollto 100
  bind < scrollto 0
  bind <A->> scrollto 100
  bind <A-<> scrollto 0
#+end_src

Hinting.
#+begin_src fundamental
  bind h hint
  bind H hint -b
  bind --mode=hint <C-g> hint.reset
  bind --mode=hint <C-n> hint.focusBottomHint
  bind --mode=hint <C-p> hint.focusTopHint
  bind --mode=hint <C-f> hint.focusRightHint
  bind --mode=hint <C-b> hint.focusLeftHint
#+end_src

Bookmarks.
#+begin_src fundamental
  bind m current_url bmark
  bind <C-x>rj fillcmdline bmarks
  bind <C-u><C-x>rj fillcmdline bmarks -t
  bind <C-x>rm current_url bmark
#+end_src

Yank URL.
#+begin_src fundamental
  bind <A-w> clipboard yank

#+end_src

Menu command line.
#+begin_src fundamental
  bind <A-x> fillcmdline_notrail
#+end_src

Escape.
#+begin_src fundamental
  bind --mode=browser <C-g> escapehatch
#+end_src

Zoom.
#+begin_src fundamental
  bind + zoom 0.1 true
  bind - zoom -0.1 true
  bind = zoom 1
#+end_src

Find.
#+begin_src fundamental
  bind <C-s> fillcmdline find
  bind --mode=ex <C-s> findnext 1
  bind --mode=ex <C-r> findnext -1
#+end_src
Navigating to new pages.
#+begin_src fundamental
  bind o fillcmdline open
  bind O fillcmdline tabopen
#+end_src

Frames.
#+begin_src fundamental
  bind <C-x>50 winclose
  bind <C-x>52 winopen
  bind <C-x><C-u>52 winopen -private
#+end_src

Tabs.
#+begin_src fundamental
  bind f tabnext
  bind b tabprev
  bind <A-f> tabmove +1
  bind <A-b> tabmove -1
  bind <C-x>b fillcmdline buffer
  bind k tabclose
  bind <C-x>k tabclose
  bind <C-x>0 tabclose
  bind q tabclose
  bind <C-x>1 tabonly
  bind <C-x>tp pin
  bind <C-x>tm mute toggle
  bind <A-g>a tabaudio
  bind <C-x>u undo
  bind <C-/> undo
#+end_src

History.
#+begin_src fundamental
  bind F forward
  bind B back
#+end_src

Textfields.
#+begin_src fundamental
  bind --mode=insert <C-d> text.delete_char
  bind --mode=insert <C-t> text.transpose_char
  bind --mode=insert <A-t> text.transpose_words
  bind --mode=insert <A-u> text.upcase_word
  bind --mode=insert <A-l> text.downcase_word
  bind --mode=insert <A-c> text.capitalize_word
  bind --mode=insert <C-k> text.kill_line
  bind --mode=insert <A-0><C-k> text.backward_kill_line
  bind --mode=insert <C-u>0<C-k> text.backward_kill_line
  bind --mode=insert <CS-Backspace> text.kill_whole_line
  bind --mode=insert <A-d> text.kill_word
  bind --mode=insert <A-Backspace> text.backward_kill_word
  bind --mode=insert <C-a> text.beginning_of_line
  bind --mode=insert <C-e> text.end_of_line
  bind --mode=insert <C-f> text.forward_char
  bind --mode=insert <C-b> text.backward_char
  bind --mode=insert <A-f> text.forward_word
  bind --mode=insert <A-b> text.backward_word
  bind --mode=insert <C-y> text.insert_text
  bind --mode=insert <C-g> composite unfocus | mode normal
#+end_src

Selection.
#+begin_src fundamental
  bind <C-Space> hint -h
  bind --mode=visual <C-g> composite js document.getSelection().empty(); mode normal; hidecmdline
  bind --mode=visual <C-n> js document.getSelection().modify("extend","forward","line")
  bind --mode=visual <C-p> js document.getSelection().modify("extend","backward","line")
  bind --mode=visual <C-b> js document.getSelection().modify("extend","backward","character")
  bind --mode=visual <C-f> js document.getSelection().modify("extend","forward","character")
  bind --mode=visual <A-f> js document.getSelection().modify("extend","forward","word")
  bind --mode=visual <A-b> js document.getSelection().modify("extend","backward","character"); document.getSelection().modify("extend","backward","word"); document.getSelection().modify("extend","forward","character")
  bind --mode=visual <A-w> composite js document.getSelection().toString() | clipboard yank
#+end_src

Commands.
#+begin_src fundamental
  bind --mode=ex <C-n> ex.next_completion
  bind --mode=ex <C-p> ex.prev_completion
  bind --mode=ex <A-n> ex.next_history
  bind --mode=ex <A-p> ex.prev_history
  bind --mode=ex <C-g> ex.hide_and_clear
  bind --mode=ex <C-f> text.forward_char
  bind --mode=ex <C-b> text.backward_char
#+end_src

Set external editor command (Emacs), and command.
#+begin_src fundamental
  set editorcmd emacsclient -a \"\" -c -e '(progn (find-file "%f") (forward-line (1- %l)) (forward-char %c))'
  bind --mode=insert <C-c><C-c> editor
  bind --mode=input <C-c><C-c> editor
#+end_src

Help.
#+begin_src fundamental
  bind <C-h><h> help
  bind <C-h><b> fillcmdline help -b
  bind <C-h><f> fillcmdline help -e
  bind <C-h><v> fillcmdline help -s
#+end_src
