#+TITLE: Isync Configuration
#+LANGUAGE: en
#+AUTHOR: David Álvarez Rosa
#+EMAIL: david@alvarezrosa.com
#+DESCRIPTION: My Isync configuration file.
#+PROPERTY: header-args :tangle mbsyncrc


Isync is a command line application to synchronize mailboxes; it supports
Maildir and IMAP4 mailboxes. New messages, message deletions and flag changes
can be propagated both ways.

Synchronization is based on unique message identifiers (UIDs), so no
identification conflicts can occur (as opposed to some other mail
synchronizers). Synchronization state is kept in one local text file per
mailbox pair; multiple replicas of a mailbox can be maintained.

The =authinfo.gpg= file should be properly configured and encrypted with, at
least, the following information.
#+begin_src conf :tangle no
  machine mail.alvarezrosa.com login david port 587 password "***pass***"
  machine smtp.yandex.com login david.alvarez.rosa port 587 password "***pass***"
#+end_src

After the first sync of emails, the =mu= database must be started. It is useful
to specify personal email addresses (e.g., for not replying to yourself in a
"Reply All").
#+begin_src conf :tangle no
  mu init -m ~/.local/share/mail --my-address=david@alvarezrosa.com --my-address=davids@alvarezrosa.com --my-address=dalvrosa@amazon.com
#+end_src


* Personal
Configuration for my personal email account.
#+begin_src conf
  IMAPAccount Personal
  Host mail.alvarezrosa.com
  User david@alvarezrosa.com
  PassCmd "gpg --no-tty -qd ~/.local/share/authinfo.gpg | grep alvarezrosa.com | awk '{print $8}'"
  SSLType IMAPS

  IMAPStore personal-remote
  Account   Personal

  MaildirStore personal-local
  Path ~/.local/share/mail/Personal/
  Inbox ~/.local/share/mail/Personal/Inbox
  SubFolders Verbatim

  Channel personal
  Far :personal-remote:
  Near :personal-local:
  Patterns *
  Create Both
  Expunge Both
  SyncState *
#+end_src

* Spam
Configuration of my spam account.
#+begin_src conf
  IMAPAccount Spam
  Host mail.alvarezrosa.com
  User davids@alvarezrosa.com
  PassCmd "gpg --no-tty -qd ~/.local/share/authinfo.gpg | grep alvarezrosa.com | awk '{print $8}'"
  SSLType IMAPS

  IMAPStore spam-remote
  Account   Spam

  MaildirStore spam-local
  Path ~/.local/share/mail/Spam/
  Inbox ~/.local/share/mail/Spam/Inbox
  SubFolders Verbatim

  Channel spam
  Far :spam-remote:
  Near :spam-local:
  Patterns *
  Create Both
  Expunge Both
  SyncState *
#+end_src

* Amazon
Configuration for my work email account.
#+begin_src conf
  IMAPAccount Amazon
  Host ballard.amazon.com
  Port 1993
  User dalvrosa
  PassCmd "gpg --no-tty -qd ~/.local/share/authinfo.gpg | grep ballard.amazon.com | awk '{print $8}'"
  SSLType IMAPS

  IMAPStore amazon-remote
  Account   Amazon

  MaildirStore amazon-local
  Path ~/.local/share/mail/Amazon/
  Inbox ~/.local/share/mail/Amazon/Inbox
  SubFolders Verbatim

  Channel amazon
  Far :amazon-remote:
  Near :amazon-local:
  Patterns * !Contacts !Journal !Notes !Tasks !Calendar
  Create Both
  Expunge Both
  SyncState *
#+end_src
* Yandex
Configuration for Yandex email account.
#+begin_src conf
  IMAPAccount Yandex
  Host imap.yandex.com
  User david.alvarez.rosa@yandex.com
  PassCmd "gpg --no-tty -qd ~/.local/share/authinfo.gpg | grep yandex.com | awk '{print $8}'"
  SSLType IMAPS

  IMAPStore yandex-remote
  Account Yandex

  MaildirStore yandex-local
  Path ~/.local/share/mail/Yandex/
  Inbox ~/.local/share/mail/Yandex/Inbox
  SubFolders Verbatim

  Channel yandex
  Far :yandex-remote:
  Near :yandex-local:
  Patterns *
  Create Both
  Expunge Both
  SyncState *
#+end_src
