#+TITLE: Xbindkeys Configuration
#+LANGUAGE: en
#+AUTHOR: David Álvarez Rosa
#+EMAIL: david@alvarezrosa.com
#+DESCRIPTION: My personal Xbindkeys configuration file.
#+PROPERTY: header-args :tangle config


Xbindkeys binds commands to keys or key combinations, works with multimedia
keys and is independent of the window manager. It is started from =.xinitrc=
as follows.
#+begin_src conf :tangle no
  xbindkeys -f ~/.config/xbindkeys/config
#+end_src

* Volume
Volume control with the laptop =Fn= keys. The default step size is 10, with
=Shift= it becomes 5 and with =Ctrl= it becomes 1.
#+begin_src conf
  "pamixer -i 10"
    XF86AudioRaiseVolume
  "pamixer -i 5"
    Shift + XF86AudioRaiseVolume
  "pamixer -i 1"
    Control + XF86AudioRaiseVolume

  "pamixer -d 10"
    XF86AudioLowerVolume
  "pamixer -d 5"
    Shift + XF86AudioLowerVolume
  "pamixer -d 1"
    Control + XF86AudioLowerVolume
#+end_src

Note that volume boost (above 100%) is possible with =pamixer -i
--allow-boost <arg>=.

Toggle mute status.
#+begin_src conf
  "pamixer -t"
    XF86AudioMute
#+end_src

* Backlight
Configuration both for display brightness and display.

** Brightness
Brightness control with the laptop =Fn= keys, using Acpilight (a
backward-compatible =xbacklight= replacement based on the ACPI interface).
The default step size is 10, with =Shift= it becomes 20 and with =Ctrl= it
becomes 5.
#+begin_src conf
  "xbacklight -inc 10"
    XF86MonBrightnessUp
  "xbacklight -inc 20"
    Shift + XF86MonBrightnessUp
  "xbacklight -inc 5"
    Control + XF86MonBrightnessUp

  "xbacklight -dec 10"
    XF86MonBrightnessDown
  "xbacklight -dec 20"
    Shift + XF86MonBrightnessDown
  "xbacklight -dec 5"
    Control + XF86MonBrightnessDown
#+end_src

** TODO Display
:LOGBOOK:
- State "TODO"       from              [2022-05-01 Sun 12:56]
:END:
*Disclaimer* Not working currently (there is a clash between the =Fn= key and
=Mod + p=), so these blocks are not tangled.

Switch off the backlight to conserve battery.
#+begin_src conf :tangle no
  "xset dpms force off"
    Mod4 + p
#+end_src

With =Ctrl= and =Shift= modifiers, toggle graphical and audio output to an
external monitor (useful when connecting the laptop to a TV).
#+begin_src conf :tangle no
  "xrandr --output HDMI-1 --auto --output eDP-1 --off; pactl set-card-profile 0 output:hdmi-stereo"
    Control + Mod4 + p
  "xrandr --output HDMI-1 --off --output eDP-1 --auto; pactl set-card-profile 0 output:hdmi-surround"
    Shift + Mod4 + p
#+end_src

* Music Player
Basic bindings for =mpd= (via =mpc=): play/pause toggle and prev/next song.
#+begin_src conf
  "mpc toggle"
    XF86AudioPlay
  "mpc prev"
    XF86AudioPrev
  "mpc next"
    XF86AudioNext
#+end_src

* Touchpad
Toggle the touchpad enabled/disabled with the laptop =Fn= key. The touchpad
name is laptop-specific (here "ELAN1200:00 04F3:309F Touchpad") and can be
found with =xinput=.
#+begin_src conf
  "if xinput list-props 'ELAN1200:00 04F3:309F Touchpad' | grep 'Device Enabled (149):.*1'; then xinput disable 'ELAN1200:00 04F3:309F Touchpad'; else xinput enable 'ELAN1200:00 04F3:309F Touchpad'; fi"
    XF86TouchpadToggle
#+end_src

*NOTE:* The key it's not working! Don't know why.

* Screen lock
Lock the screen with =Super+l= using =slock= from Suckless.
#+begin_src conf
  "slock"
    Mod2 + Mod4 + l
#+end_src

* Screenshot
Take screenshots with =maim= (=-u= hides the cursor): full screen, active
window (=Shift=) or selection (=Ctrl=). The image is saved to =~/tmp= and
copied to the clipboard.
#+begin_src conf
  "maim -u | tee ~/tmp/$(date +'%Y%m%d-%H:%M:%S').png | xclip -selection clipboard -t image/png"
    Print
  "maim -u --window $(xdotool getactivewindow) | tee ~/tmp/$(date +'%Y%m%d-%H:%M:%S').png | xclip -selection clipboard -t image/png"
    Shift + Print
  "maim -u --select | tee ~/tmp/$(date +'%Y%m%d-%H:%M:%S').png | xclip -selection clipboard -t image/png"
    Control + Print
#+end_src

* Application Launcher
Launch applications with dmenu.
#+begin_src conf
  "dmenu_run -fn 'Hack:size=11'"
    Mod4 + d
#+end_src

* TODO More ideas
:PROPERTIES:
:header-args: :tangle no
:END:
** From i3
#+begin_src conf
  # Apagar el ordenador.
  bindsym $mod+x                  exec --no-startup-id ~/.scripts/i3shutdown
  bindsym $mod+Shift+x            exec --no-startup-id ~/.scripts/i3reboot
#+end_src

#+begin_src conf
  # Comando para abrir Transmission (para los torrents).
  bindsym $mod+Shift+t exec --no-startup-id "(pgrep -x transmission-da > /dev/null || (transmission-daemon && notify-send 'Transmission daemon' 'Starting transmission daemon...')) && st -t Transmission tremc"

  # Comando para actualizar el correo.
  bindsym $mod+Shift+m exec --no-startup-id "~/.scripts/cronjobs/updateMail '' 'yes'"
  #+end_src

#+begin_src conf
  # Abrir "rofi": menú para lanzar programas.
  bindsym $mod+r exec rofi -show drun
#+end_src

** Network Manager
Toggle Wi-Fi enabled/disabled using =nmcli=, the command-line tool for
NetworkManager. The current status can be checked with =nmcli radio wifi=.
#+begin_src conf
  "[[ $(nmcli radio wifi) == 'enabled' ]] && nmcli radio wifi off || nmcli radio wifi on"
    XF86WLAN
#+end_src

*** TODO Think about changing to this
:LOGBOOK:
- State "TODO"       from              [2021-09-02 Thu 08:40]
- State "TODO"       from              [2021-09-02 Thu 08:40]
:END:
This approach might be a better alternative (in general for all commands), but
only needed if not using any status bar.
#+begin_src conf :tangle no
  "nmcli radio wifi off"
    XF86WLAN
  "nmcli radio wifi on"
    Control + XF86WLAN
#+end_src
